apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django
          image: python:3.10.12
          volumeMounts:
            - name: app-volume
              mountPath: /app
          command: [ "bash", "-c", "pip3 install --no-cache-dir -r /clustering/requirements.txt 
          && python3 /clustering/manage.py collectstatic --noinput 
          && python3 /clustering/manage.py migrate 
          && gunicorn myproject.wsgi:application --bind 0.0.0.0:8000" ]
      volumes:
        - name: app-volume
          hostPath:
            path: /path/to/your/app