apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydjangoapp
  template:
    metadata:
      labels:
        app: mydjangoapp
    spec:
      containers:
      - name: mydjangoapp
        image: mydjangoapp  # Replace with the image name from Docker
        ports:
        - containerPort: 8000