version: '3.8'

services:
  django:
    image: python:3.10.12
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.type == worker
    volumes:
      - ./clustering:/clustering
    command: >
      bash -c "pip3 install --no-cache-dir -r /clustering/requirements.txt 
      && python3 /clustering/manage.py collectstatic --noinput 
      && python3 /clustering/manage.py migrate && gunicorn myproject.wsgi:application --bind 0.0.0.0:8000"

  nginx:
    image: nginx
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == loadbalancer
      restart_policy:
        condition: on-failure
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
