# Use the official Python base image
FROM python:3.10.12

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Install dependencies
COPY clustering/requirements.txt .
RUN pip3 install -r requirements.txt

# Copy the Django project
COPY . .

# Expose port for the Django app
EXPOSE 8000

# Start the Django development server
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]